GadgetCart-main/adminpanel/urls.py
from os import name
from django.urls import path

from . import views

urlpatterns = [
    path("", views.adminpanel, name="adminpanel"),
    path("adminsignin/", views.adminsignin, name="adminsignin"),
    path("adminsignout/", views.adminsignout, name="adminsignout"),
    path("productlist/", views.productlist, name="productlist"),
    path("productadd/", views.productadd, name="productadd"),
    path("productdelete/<int:product_id>/", views.productdelete, name="productdelete"),
    path("productedit/<int:product_id>/", views.productedit, name="productedit"),
    path("categorylist/", views.categorylist, name="categorylist"),
    path("categoryadd/", views.categoryadd, name="categoryadd"),
    path(
        "categorydelete/<int:category_id>/", views.categorydelete, name="categorydelete"
    ),
    path("categoryedit/<int:category_id>/", views.categoryedit, name="categoryedit"),
    path("brandlist/", views.brandlist, name="brandlist"),
    path("brandadd/", views.brandadd, name="brandadd"),
    path("branddelete/<int:brand_id>/", views.branddelete, name="branddelete"),
    path("brandedit/<int:brand_id>/", views.brandedit, name="brandedit"),
    path("variantadd/", views.variantadd, name="variantadd"),
    path("userdetails/", views.userdetails, name="userdetails"),
    path("userdelete/<int:account_id>/", views.userdelete, name="userdelete"),
    path("block_user/<int:account_id>/", views.block_user, name="block_user"),
    path("unblock_user/<int:account_id>/", views.unblock_user, name="unblock_user"),
    path("brand_offer_add/", views.brand_offer_add, name="brand_offer_add"),
    path("category_offer_add/", views.category_offer_add, name="category_offer_add"),
    path("product_offer_add/", views.product_offer_add, name="product_offer_add"),
    path("product_offer_list/", views.product_offer_list, name="product_offer_list"),
    path(
        "product_offer_delete/<int:id>",
        views.product_offer_delete,
        name="product_offer_delete",
    ),
    path("category_offer_list/", views.category_offer_list, name="category_offer_list"),
    path(
        "category_offer_delete/<int:id>",
        views.category_offer_delete,
        name="category_offer_delete",
    ),
    path("brand_offer_list/", views.brand_offer_list, name="brand_offer_list"),
    path(
        "brand_offer_delete/<int:id>",
        views.brand_offer_delete,
        name="brand_offer_delete",
    ),
    path("active_orders/", views.active_orders, name="active_orders"),
    path(
        "active_orders_edit/<int:order_id>/",
        views.active_orders_edit,
        name="active_orders_edit",
    ),
    path("order_history/", views.order_history, name="order_history"),
    path("order_details/<int:id>/", views.order_details, name="order_details"),
    path("banner_list/", views.banner_list, name="banner_list"),
    path("banner_add/", views.banner_add, name="banner_add"),
    path("banner_delete/<int:banner_id>", views.banner_delete, name="banner_delete"),
    path("report/", views.report, name="report"),
    path("coupon_list/", views.coupon_list, name="coupon_list"),
    path("coupon_add/", views.coupon_add, name="coupon_add"),
    path("coupon_delete/<int:coupon_id>/", views.coupon_delete, name="coupon_delete"),
    path("redeemed_coupons/", views.redeemed_coupons, name="redeemed_coupons"),
    path("brands_pdf/", views.brands_pdf, name="brands_pdf"),
    path("orders_pdf/", views.orders_pdf, name="orders_pdf"),
    path("products_pdf/", views.products_pdf, name="products_pdf"),
    path("sales_pdf/", views.sales_pdf, name="sales_pdf"),
    path("orders_csv/", views.orders_csv, name="orders_csv"),
    path("brands_csv/", views.brands_csv, name="brands_csv"),
    path("products_csv/", views.products_csv, name="products_csv"),
    path("sales_csv/", views.sales_csv, name="sales_csv"),
]

GadgetCart-main/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("checkout/", views.checkout, name="checkout"),
    path("buy_now/<int:product_id>/", views.buy_now, name="buy_now"),
]

GadgetCart-main/gadgetcart/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    path("accounts/", include("accounts.urls")),
    path("store/", include("store.urls")),
    path("carts/", include("carts.urls")),
    path("offer/", include("offer.urls")),
    # Orders
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GadgetCart-main/adminpanel/models.py
from django.db import models

# Create your models here.

GadgetCart-main/store/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from category.models import Category
from brand.models import Brand
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count
from django.db.models.aggregates import Sum
from django.utils import timezone
from django.apps import apps

# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=900, blank=True)
    price = models.IntegerField()
    image1 = models.ImageField(upload_to="photos/products")
    image2 = models.ImageField(upload_to="photos/products")
    image3 = models.ImageField(upload_to="photos/products")
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse("product_detail", args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            average=Avg("rating")
        )
        avg = 0
        if reviews["average"] is not None:
            avg = float(reviews["average"])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(
            count=Count("rating")
        )
        count = 0
        if reviews["count"] is not None:
            count = int(reviews["count"])
        return count

    def get_price(self):
        try:
            if self.productoffer.is_active:
                offer_price = (self.price / 100) * self.productoffer.discount_offer
                price = self.price - offer_price
                return {"price": price, "discount": self.productoffer.discount_offer}
            raise
        except:
            try:
                if self.category.categoryoffer.is_active:
                    offer_price = (
                        self.price / 100
                    ) * self.category.categoryoffer.discount_offer
                    price = self.price - offer_price
                    return {
                        "price": price,
                        "discount": self.category.categoryoffer.discount_offer,
                    }
                raise
            except:
                try:
                    if self.brand.brandoffer.is_active:
                        offer_price = (
                            self.price / 100
                        ) * self.brand.brandoffer.discount_offer
                        price = self.price - offer_price
                        return {
                            "price": price,
                            "discount": self.brand.brandoffer.discount_offer,
                        }
                    raise
                except:
                    print("----else----")
                return {"price": self.price}

    def get_revenue(self, month=timezone.now().month):
        orderproduct = apps.get_model("orders", "OrderProduct")
        orders = orderproduct.objects.filter(
            product=self, created_at__month=month, status="Delivered"
        )
        return orders.values("product").annotate(revenue=Sum("product_price"))

    def get_profit(self, month=timezone.now().month):
        orderproduct = apps.get_model("orders", "OrderProduct")
        orders = orderproduct.objects.filter(
            product=self, created_at__month=month, status="Delivered"
        )
        profit_calculted = orders.values("product").annotate(
            profit=Sum("product_price")
        )
        profit_calculated = profit_calculted[0]["profit"] * 0.23
        return profit_calculated

    def get_count(self, month=timezone.now().month):
        orderproduct = apps.get_model("orders", "OrderProduct")
        orders = orderproduct.objects.filter(
            product=self, created_at__month=month, status="Delivered"
        )
        return orders.values("product").annotate(quantity=Sum("quantity"))


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(
            variation_category="color", is_active=True
        )


variation_category_choices = (("color", "Color"),)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100, choices=variation_category_choices
    )
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

GadgetCart-main/templates/adminpanel/active_orders.html
{% extends 'adminpanel/base.html' %}

{% load static %}

{% block content %}

<style>
    .table td{
        text-align: center;
    }
</style>

<!-- Start Content-->


<div class="container">
    <h4 class="ml-3 mt-4 mb-4">ACTIVE ORDERS</h4>

    {% include 'adminpanel/includes/alerts.html' %}

    <div class="col-12" id="tables">
        <table class="table table-striped table-bordered table-hover bg-white bg-body shadow" id="myTable">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Customer name</th>
                    <th>Product</th>
                    <th>Total Price</th>
                    <th>Quantity</th>
                    <th>Order Status</th>
                    <th>Order Date</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                {% for order in active_orders %}
                <tr>
                    <th scope="row"> {{forloop.counter}} </th>
                    <td><a href="{% url 'order_details' order.id %} " class="text-dark">{{order.user.full_name}}</a></td>
                    <td>{{order.product}}</td>

                    <td>
                        {{ order.product.get_price.price }}
                    </td>
                    <td>
                        {{order.quantity}}
                    </td>
                    <td>
                        {{order.status}}
                    </td>
                    <td>
                        {{order.updated_at}}
                    </td>
                    <td>
                        <a href="{% url 'active_orders_edit' order.id %}" class="btn btn-outline-primary">Edit</a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>



<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->



<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

{% endblock %}

GadgetCart-main/templates/adminpanel/active_orders_edit.html
{% extends 'adminpanel/base.html' %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}


{% block title %} Edit Brand {% endblock %}

{% load static %}

{% block content %}
<!-- Start Content-->


<div class="card mx-auto mt-4" style="max-width:700px;">
    <article class="card-body">
        <div class="container col-10">
            <div class="container-fluid text-center ">
                <h4 class="ml-5 mt-3 mb-3 text-black">EDIT ORDER</h4>

            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
					<div id="image-box" class="image-container"></div>
			
					<button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;"
						type="submit">Post</button>
				</div>
            </form>
        </div>
    </article>
</div>


<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->



{% endblock %}

GadgetCart-main/templates/adminpanel/adminpanel.html
{% extends 'adminpanel/base.html' %}
{% load humanize %}
{% block content %}

         <!-- start page title -->
         <div class="row">
            <div class="col-12">
                <div class="page-title-box ml-4">
                    
                    <h4 class="page-title">DASHBOARD.</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 


    <div class="bg-primary pt-10 pb-21"></div>
    <div class="container-fluid mt-n22 px-6">
        <div class="row">
            <div class="col-xl-3 col-lg-6 col-md-12 col-12">
                <!-- card -->
                <div class="card rounded-3">
                    <!-- card body -->
                    <div class="card-body">
                        <!-- heading -->
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div>
                                <h4 class="mb-0">Total Orders</h4>
                            </div>
                        </div>
                        <!-- project number -->
                        <div>
                            <h2 class="fw-bold">{{total_orders | intcomma }}</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-3 col-lg-6 col-md-12 col-12">
                <!-- card -->
                <div class="card rounded-3">
                    <!-- card body -->
                    <div class="card-body">
                        <!-- heading -->
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div>
                                <h4 class="mb-0">Total Users</h4>
                                
                            </div>
                        </div>
                        <!-- project number -->
                        <div>
                            <h2 class="fw-bold">{{users}}</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-3 col-lg-6 col-md-12 col-12">
                <!-- card -->
                <div class="card rounded-3">
                    <!-- card body -->
                    <div class="card-body">
                        <!-- heading -->
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div>
                                <h4 class="mb-0">Total Revenue</h4>
                            </div>
                        </div>
                        <!-- project number -->
                        <div>
                            <h2 class="fw-bold">₹{{ total_revenue | floatformat:"0" | intcomma }}</h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-3 col-lg-6 col-md-12 col-12">
                <!-- card -->
                <div class="card rounded-3">
                    <!-- card body -->
                    <div class="card-body">
                        <!-- heading -->
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div>
                                <h4 class="mb-0">Total Products</h4>
                            </div>
                        </div>
                        <!-- project number -->
                        <div>
                            <h2 class="fw-bold">{{products}}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        
        <div class="row mt-7 d-flex justify-content-evenly">
            <div class="col-12 col-lg-5 card">
                <canvas id="statusChart" width="300" height="300"></canvas>
            </div>
            <div class="col-12 col-lg-5 card ">
                <canvas id="transaction" width="300" height="300"></canvas>
            </div>
            <div class="col-12 col-lg-5 card mt-5">
                <canvas id="chart3" width="300" height="300"></canvas>
            </div>
            <div class="col-12 col-lg-5 card mt-5">
                <canvas id="leading-brands" width="300" height="300"></canvas>
            </div>
        </div>
    </div>

    



<script>
    // chart-1 Order status
    const ctx = document.getElementById('statusChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['New Order', 'Order Accepted', 'Shipped', 'Out For Delivery', 'Delivered', 'Cancelled order'],
            datasets: [{
                label: 'Order Status',
                data: {{ status_counter }},
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(255, 205, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(153, 102, 255, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    
    // chart-2 Payments methods
    const transactionData = {
        labels: [
            
            {% for i in brands_list %}
            '{{ i }}',
            {% endfor %}
        ],
        datasets: [{
            label: 'Brands',
            data: {{ products_count }},
            backgroundColor: [
                'rgb(255, 99, 132)',
                'rgb(54, 162, 235)',
                'rgb(255, 205, 86)'
            ],
            hoverOffset: 4
        }]
    };
    const transaction = document.getElementById('transaction').getContext('2d');
    const myTransactionChart = new Chart(transaction, {
        type: 'doughnut',
        data: transactionData,
    })

 // chart-3 Weekly orders
 const ctx3 = document.getElementById('chart3').getContext('2d');
 const chart3 = new Chart(ctx3, {
     type: 'line',
     data: {
         labels: {{last_week_days|safe}},
         datasets: [{
             label: 'Orders',
             data: {{ last_week_orders|safe }},
             borderWidth: 1,
             borderColor: 'rgb(75, 192, 192)',
             tension: 0.1,
             fill: false,
         }]
     },
     options: {
         scales: {
             y: {
                 beginAtZero: true
             }
         }
     }
 });

  //cahrt-4 Brands
  const leadingBrandsLabel = [
        'Paypal',
        'Cash on Delivary',
        'Razorpay'
];
const leadingBrandsData = {
  labels: leadingBrandsLabel,
  datasets: [{
      label: 'Payment Methods',
      data:  {{ payment_method_status }} ,
      backgroundColor: [
          'rgba(255, 99, 132, 0.7)',
          'rgba(255, 159, 64, 0.7)',
          'rgba(255, 205, 86, 0.7)',
          'rgba(75, 192, 192, 0.7)',
          'rgba(54, 162, 235, 0.7)',
          'rgba(153, 102, 255, 0.7)',
          'rgba(201, 203, 207, 0.7)'
      ],
      borderColor: [
          'rgb(255, 99, 132)',
          'rgb(255, 159, 64)',
          'rgb(255, 205, 86)',
          'rgb(75, 192, 192)',
          'rgb(54, 162, 235)',
          'rgb(153, 102, 255)',
          'rgb(201, 203, 207)'
      ],
      borderWidth: 1
  }]
};
const leadingBrand = document.getElementById('leading-brands').getContext('2d');
const leadingBrandChart = new Chart(leadingBrand, {
  type: 'bar',
  data: leadingBrandsData,
  options: {
      scales: {
          y: {
              beginAtZero: true,
          },
      }
  },
})


</script>


{% endblock %}

GadgetCart-main/templates/adminpanel/brand_offer_add.html
{% extends 'adminpanel/base.html' %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% load static %}

{% block content %}
<!-- Start Content-->




<div class="card mx-auto mt-4" style="max-width:700px;">
    <article class="card-body">
        <div class="container col-10">
            <div class="container-fluid text-center ">
                <h4 class="ml-5 mt-3 mb-3 text-black">ADD BRAND</h4>

            </div>
            {% include 'adminpanel/includes/alerts.html' %}
            <form action="{% url 'brand_offer_add' %}" method="post" >
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
				
					
					<button class="btn btn-outline-info" id="confirm-btn" style="width: 100%; margin-top: 10px;"
						type="submit">Post</button>
				</div>
            </form>
        </div>
    </article>
</div>


<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->





{% endblock %}

GadgetCart-main/templates/adminpanel/coupon_add.html
{% extends 'adminpanel/base.html' %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% load static %}

{% block content %}
<!-- Start Content-->




<div class="card mx-auto mt-4" style="max-width:700px;">
    <article class="card-body">
        <div class="container col-10">
            <div class="container-fluid text-center ">
                <h4 class="ml-5 mt-3 mb-3 text-black">ADD VARIANT</h4>

            </div>
            {% include 'adminpanel/includes/alerts.html' %}
            <form action="{% url 'coupon_add' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="form-group">
					<div id="image-box" class="image-container"></div>
					
					<button class="btn btn-outline-info" style="width: 100%; margin-top: 10px;" type="submit">Post</button>
				</div>
            </form>
        </div>
    </article>
</div>


<!-- Footer Start -->
<footer class="footer">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6">
				<script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
			</div>
			<div class="col-md-6">
				<div class="text-md-end footer-links d-none d-md-block">
					<a href="javascript: void(0);">About</a>
					<a href="javascript: void(0);">Support</a>
					<a href="javascript: void(0);">Contact Us</a>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- end Footer -->





{% endblock %}

GadgetCart-main/templates/adminpanel/productlist.html
{% extends 'adminpanel/base.html' %}

{% load static %}

{% block content %}
<!-- Start Content-->


<div class="container">
    <div class="row">
        <div class="col">
            <h4 class="ml-3 mt-4 mb-4">PRODUCT LIST</h4>
        </div>
        <div class="col">
            
            <a href="{% url 'productadd' %}" type="button" class="btn btn-primary mt-4 mr-3 float-right">Add Product</a>
            <a href="{% url 'variantadd' %}" type="button" class="btn btn-primary mt-4 mr-3 float-right">Add Variant</a>
        </div>
    </div>

    {% include 'adminpanel/includes/alerts.html' %}

    <div class="col-12" id="tables">
        <table class="table table-striped table-bordered table-hover bg-white bg-body shadow" id="myTable">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Variants</th>
                    <th>Price</th>
                    <th>Brand</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td class="table-user">
                        <img src="{{ product.image1.url }}" alt="table-user" />
                        {{ product.product_name }}
                    </td>
                   
                    <td class="align-middle">
                        {% for i in product.variation_set.all %}
                        {{ i }} <br>
                        {% endfor %}
                    </td>
                
                   
                    <td class="align-middle">₹{{ product.price }}</td>
                    <td class="align-middle">{{ product.brand }}</td>
                    <td class="align-middle">{{ product.category }}</td>
                    <td class="table-action align-middle">
                        <center>

                            <a href="{% url 'productedit' product.id %}"><span class="material-icons">edit</span></a>

                            <a href="{% url 'productdelete' product.id %}" onclick="deleteItems(event)"><span
                                    class="material-icons">delete</span></a>
                        </center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>



<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->



<script>
    function approve() {
        event.preventDefault();
        var linkURL = event.currentTarget.href;
        var name = event.currentTarget.name;
        console.log(linkURL)
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
            }
        })
    }
</script>


<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>


<style>
    .table .table-user img {
        height: 100px;
        width: 100px;
    }
</style>

{% endblock %}